name: SSL Test with PHP

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            php: 8.3
            should_fail: false
          - os: macos-latest
            php: 8.3
            should_fail: false
          - os: windows-latest
            php: 7.2
            should_fail: true
          - os: windows-latest
            php: 7.3
            should_fail: true
          - os: windows-latest
            php: 7.4
            should_fail: true
          - os: windows-latest
            php: 8.0
            should_fail: true
          - os: windows-latest
            php: 8.1
            should_fail: true
          - os: windows-latest
            php: 8.2
            should_fail: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: curl
        coverage: none
    
    - name: Print and delete CA certificate file
      run: |
        type "C:\tools\php\ssl\cacert.pem"
        del "C:\tools\php\ssl\cacert.pem"
      if: runner.os == 'Windows'

    - name: PHP -i
      run: php -i

    - name: Run SSL Test Script
      env:
        OPENSSL_CONF: ''
      run: php -d openssl.cafile='' ssl_test.php ${{ matrix.should_fail }}
