name: SSL Test with PHP

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            php: 8.3
            should_fail: false
          - os: macos-latest
            php: 8.3
            should_fail: false
          - os: windows-latest
            php: 7.2
            should_fail: true
          - os: windows-latest
            php: 7.3
            should_fail: true
          - os: windows-latest
            php: 7.4
            should_fail: true
          - os: windows-latest
            php: 8.0
            should_fail: true
          - os: windows-latest
            php: 8.1
            should_fail: true
          - os: windows-latest
            php: 8.2
            should_fail: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: curl
        coverage: none

    - name: Remove Custom CA Configuration (Windows)
      if: runner.os == 'Windows'
      run: |
        $phpIni = (php --ini | Select-String 'Loaded Configuration File').Line.Split(' ')[-1]
        if ($phpIni -ne $null) {
          "curl.cainfo=`"" | Out-File -FilePath $phpIni -Append
          "openssl.cafile=`"" | Out-File -FilePath $phpIni -Append
        }
        echo "OPENSSL_CONF=" | Out-File -FilePath $env:GITHUB_ENV -Append
      shell: pwsh
    
    - name: Remove Custom CA Configuration (Linux/Mac)
      if: runner.os != 'Windows'
      run: |
        phpIni=$(php --ini | grep 'Loaded Configuration File' | awk '{print $NF}')
        echo "curl.cainfo=" >> "$phpIni"
        echo "openssl.cafile=" >> "$phpIni"
        echo "OPENSSL_CONF=" >> "$GITHUB_ENV"
      shell: bash

    - name: Run SSL Test Script
      env:
        OPENSSL_CONF: ''
      run: php ssl_test.php ${{ matrix.should_fail }}
